Repository ipython/ipython, pull requests merged in 2021-12, with the labels that each got.

#13373 Tweak tests for PyPy and add CI runner
  .github/workflows/test.yml
  IPython/core/tests/test_async_helpers.py
  IPython/core/tests/test_debugger.py
  IPython/core/tests/test_magic.py
  IPython/core/tests/test_run.py
  IPython/core/tests/test_ultratb.py
  IPython/extensions/tests/test_autoreload.py
  IPython/terminal/tests/test_debug_magic.py
  IPython/terminal/tests/test_embed.py
  IPython/testing/plugin/show_refs.py
  IPython/testing/plugin/test_refs.py
  IPython/utils/ipstruct.py
Labels: Numfocus SDG 2021

#13371 Refactor inspect.getabsfile/getsource/getsourcelines + handle OSError + tests
  IPython/core/oinspect.py
  IPython/core/tests/test_oinspect.py
Labels: Numfocus SDG 2021

#13390 remove deprecated hooks
  IPython/core/hooks.py
  IPython/core/interactiveshell.py
Labels: 8.0 what's new, deprecation/removal

#12984 use time.process_time instead of perf_counter
  IPython/core/magics/execution.py
  IPython/utils/timing.py
  docs/source/whatsnew/development.rst
  docs/source/whatsnew/pr/12984-process-time.rst
Labels: magics

#12586 Automatic matching of brackets and quotes
  IPython/terminal/interactiveshell.py
  IPython/terminal/shortcuts.py
Labels: hacktoberfest-accepted
