Repository ipython/ipython, pull requests merged in 2023-02, with the labels that each got.

#13918 Fix typos and grammar in 8.x changelog
  docs/source/whatsnew/version8.rst
Labels: documentation

#13928 Allow to customise shortcuts using a traitlet
  IPython/terminal/interactiveshell.py
  IPython/terminal/shortcuts/__init__.py
  IPython/terminal/shortcuts/auto_match.py
  IPython/terminal/shortcuts/auto_suggest.py
  IPython/terminal/shortcuts/filters.py
  IPython/terminal/tests/test_interactivshell.py
  IPython/terminal/tests/test_shortcuts.py
  docs/autogen_shortcuts.py
  docs/environment.yml
  docs/source/config/details.rst
  docs/source/config/shortcuts/index.rst
  docs/source/whatsnew/pr/shortcuts-config-traitlet.rst
Labels: autosuggestions

#13943 Strip prefix in `attr_matches` result
  IPython/core/completer.py
  IPython/core/tests/test_completer.py
Labels: tab-completion

#13774 Shaperilio/autoreload verbosity
  IPython/extensions/autoreload.py
  IPython/extensions/tests/test_autoreload.py
  docs/source/whatsnew/pr/autoreload-verbosity.rst
Labels: magics

#13945 add a little detail to custom repr method docs
  docs/source/config/integrating.rst
Labels: documentation
