Repository ipython/ipython, pull requests merged in 2023-06, with the labels that each got.

#14080 Add pass-through filter for shortcuts
  IPython/terminal/shortcuts/__init__.py
  IPython/terminal/shortcuts/auto_suggest.py
  IPython/terminal/shortcuts/filters.py
  docs/autogen_shortcuts.py
Labels: autosuggestions

#14056 Add option to `%autoreload` to hide errors when reloading code
  IPython/extensions/autoreload.py
Labels: magics

#14055 Use module and method descriptor types declared in the `types` module
  IPython/core/guarded_eval.py
Labels: tab-completion
